replaced local calls with a thrift ones
rbkmoney/hellgate pull request #557
Opened 2021-03-30 07:27 UTC by yuri-bukhalenkov

2021-03-30 23:18 UTC, ndiezel0 requested changes

2021-03-30 23:18 UTC, ndiezel0 commented on apps/hellgate/src/hg_invoice_payment_chargeback.erl
> +    {ok, PartyRevision} = party_client_thrift:get_revision(PartyId, Client, Context),
У нас ревизия есть в структуре `#domain_Party`, запрашивать ее снова нет смысла.

2021-03-30 23:18 UTC, ndiezel0 commented on apps/hellgate/src/hg_invoice_payment_chargeback.erl
> +    Contract.
Контракты у нас есть в структуре `#domain_Party`, из которой можно их достать с помощью `hg_party:get_contract/2`.

2021-03-30 23:18 UTC, ndiezel0 commented on apps/hellgate/src/hg_invoice_payment_chargeback.erl
> -    _ = validate_contract_active(Contract),
А зачем была убрана эта валидация?

2021-03-30 23:18 UTC, ndiezel0 commented on apps/hellgate/src/hg_recurrent_paytool.erl
> +    {ok, PartyRevision} = party_client_thrift:get_revision(PartyId, Client, Context),
Опять же, ревизия у нас и так под рукой, не нужно за ней ходить в PM.

2021-03-31 06:36 UTC, yuri-bukhalenkov commented on apps/hellgate/src/hg_invoice_payment_chargeback.erl
>      Shop = pm_party:get_shop(ShopID, Party),
да, меня этот копи паст тоже смутил. Правда, я не знал какой из двух лишний.

2021-03-31 06:41 UTC, yuri-bukhalenkov commented on apps/hellgate/src/hg_invoice_payment_chargeback.erl
> +    {ok, PartyRevision} = party_client_thrift:get_revision(PartyId, Client, Context),
на всякий случай, ты про пати-ревижн? а-то дохера тут всяких ревизий: пати-ревижн, домэйн-ревижн, просто ревижн.

2021-03-31 06:46 UTC, yuri-bukhalenkov commented on apps/hellgate/src/hg_invoice_payment_chargeback.erl
> -    _ = validate_contract_active(Contract),
а где тут контракт? по коду мы получаем термсы контракта, а сам контракт остаётся где-то в пати-менеджере.

2021-03-31 06:47 UTC, yuri-bukhalenkov commented on apps/hellgate/src/hg_recurrent_paytool.erl
> +    {ok, PartyRevision} = party_client_thrift:get_revision(PartyId, Client, Context),
ок.

2021-03-31 08:11 UTC, ndiezel0 commented on apps/hellgate/src/hg_invoice_payment_chargeback.erl
> -    _ = validate_contract_active(Contract),
Контракт в пати.

2021-03-31 08:11 UTC, ndiezel0 commented on apps/hellgate/src/hg_invoice_payment_chargeback.erl
> +    {ok, PartyRevision} = party_client_thrift:get_revision(PartyId, Client, Context),
Да, я про пати ревижн.

2021-03-31 08:12 UTC, yuri-bukhalenkov commented on apps/hellgate/src/hg_invoice_payment_chargeback.erl
>      Shop = pm_party:get_shop(ShopID, Party),
исправил

2021-03-31 08:13 UTC, yuri-bukhalenkov commented on apps/hellgate/src/hg_invoice_payment_chargeback.erl
> +    {ok, PartyRevision} = party_client_thrift:get_revision(PartyId, Client, Context),
ок. исправил.

2021-03-31 08:13 UTC, yuri-bukhalenkov commented on apps/hellgate/src/hg_invoice_payment_chargeback.erl
> +    Contract.
исправил

2021-03-31 08:13 UTC, yuri-bukhalenkov commented on apps/hellgate/src/hg_recurrent_paytool.erl
> +    {ok, PartyRevision} = party_client_thrift:get_revision(PartyId, Client, Context),
исправил

2021-03-31 08:46 UTC, ndiezel0 commented on apps/hellgate/src/hg_invoice.erl
> +    {ok, PartyRevision} = party_client_thrift:get_revision(PartyId, Client, Context),
Здесь тоже можно от этого избавиться.

2021-03-31 08:46 UTC, ndiezel0 commented on apps/hellgate/src/hg_recurrent_paytool.erl
> -    throw(#payproc_InvalidContractStatus{status = Status}).
Этот ассерт надо бы добавить в тех местах, где был вызов `get_merchant_recurrent_paytools_terms/4`

2021-03-31 08:48 UTC, ndiezel0 commented on apps/hellgate/src/hg_invoice_payment_chargeback.erl
> -    _ = validate_contract_active(Contract),
Куда именно? Мне собственно важно только, чтобы осталась валидация.

2021-03-31 08:52 UTC, yuri-bukhalenkov commented on apps/hellgate/src/hg_invoice_payment_chargeback.erl
> -    _ = validate_contract_active(Contract),
ща, закоммичу....

2021-03-31 09:26 UTC, yuri-bukhalenkov commented on apps/hellgate/src/hg_invoice_payment_chargeback.erl
> -    _ = validate_contract_active(Contract),
вернул

2021-03-31 09:27 UTC, yuri-bukhalenkov commented on apps/hellgate/src/hg_recurrent_paytool.erl
> -    throw(#payproc_InvalidContractStatus{status = Status}).
вернул

2021-03-31 15:06 UTC, ndiezel0 approved these changes

2021-03-31 15:08 UTC, merged