ED-110: dictionaries replacement
rbkmoney/hellgate pull request #575
Opened 2021-06-16 08:58 UTC by yuri-bukhalenkov

2021-06-21 13:03 UTC, kpy3 reviewed
Не-не, оно не так работает, будут справочники (уже есть) в которых будут прописаны данные платёжных систем, а так же ссылка для сопоставления старых и новых значений.

2021-06-21 13:11 UTC, yuri-bukhalenkov commented
А как и где о них узнать?

2021-06-21 13:11 UTC, yuri-bukhalenkov commented
> Не-не, оно не так работает, будут справочники (уже есть) в которых будут прописаны данные платёжных систем, а так же ссылка для сопоставления старых и новых значений.

А как и где о них узнать?

2021-06-21 13:46 UTC, kpy3 commented
> > Не-не, оно не так работает, будут справочники (уже есть) в которых будут прописаны данные платёжных систем, а так же ссылка для сопоставления старых и новых значений.
> 
> А как и где о них узнать?

У меня :) Могу рассказать

2021-06-21 14:14 UTC, yuri-bukhalenkov commented
> > > Не-не, оно не так работает, будут справочники (уже есть) в которых будут прописаны данные платёжных систем, а так же ссылка для сопоставления старых и новых значений.
> > 
> > 
> > А как и где о них узнать?
> 
> У меня :) Могу рассказать

Плись 🙏

2021-08-12 11:05 UTC, kpy3 commented
@yuri-bukhalenkov конфликты

2021-08-12 11:13 UTC, yuri-bukhalenkov commented
> @yuri-bukhalenkov конфликты

да, с тех пор мастер ушёл вперёд. сейчас разрулю

2021-08-12 12:52 UTC, yuri-bukhalenkov commented
> @yuri-bukhalenkov конфликты
готово

2021-08-19 07:28 UTC, kpy3 requested changes

2021-08-19 07:28 UTC, kpy3 commented on apps/hellgate/src/hg_payment_tool.erl
> +) when PaymentSystem /= undefined ->
Micro: Странно, почему везде теперь PS, а тут PaymentSystem осталось?

2021-08-19 07:28 UTC, kpy3 commented on apps/hellgate/src/hg_payment_tool.erl
> +get_possible_methods({bank_card, #domain_BankCard{payment_system = PS} = BankCard}) when PS /= undefined ->
Не проще ли сразу в одном месте перекладывать и payment_system и payment_system_deprecated и поля, связанные с токенами? В таком разделении вижу опасность того что совместимость сломается. Собственно нам эта логика не нужна, эту логику у себя адаптеры делают, нам надо обогатить наши структуры новыми данными, а решать какие использовать клиенты будут.

2021-08-19 07:28 UTC, kpy3 commented on apps/hellgate/src/hg_payment_tool.erl
> +get_possible_methods({digital_wallet, #domain_DigitalWallet{payment_service = PS}}) when PS /= undefined ->
Коммент выше относится для всех структур с депрекейтед. :)

2021-08-19 07:28 UTC, kpy3 commented on apps/hellgate/src/hg_payment_tool.erl
> +        <<"euroset">> -> #domain_PaymentTerminal{terminal_type_deprecated = euroset};
Вот это кажется странным, terminal_type_deprecated должен быть заполнен всегда ЕМНИП, а идентификаторы терминалов не факт что будут с такими же id. Кажется этот код лишний.

2021-08-19 07:28 UTC, kpy3 commented on apps/hellgate/src/hg_payment_tool.erl
> +        <<"wechat">> -> #domain_PaymentTerminal{terminal_type_deprecated = wechat};
На будущее: давай не будем смешивать рефакторинги с основной задачей, сбивает с толку и уводит нить ревью в сторону. Трудно разбираться к чему это, а так же может повлиять в будущем на разбор инцидентов в худшую сторону.

2021-08-19 07:57 UTC, yuri-bukhalenkov commented on apps/hellgate/src/hg_payment_tool.erl
> +) when PaymentSystem /= undefined ->
где можно было путём сокращения разместить выражение в одну строчку я заменил на PS, а где бессмысленно оставил как есть.

2021-08-30 08:08 UTC, arikai commented on apps/hellgate/src/hg_payment_tool.erl
> +    setelement(Field, BCard, Value).
ИМХО, как вариант для удобства ревью это можно разносить на 2 PR: один с рефакторингом старого кода, а второй – непосредственно изменения, необходимые для задачи (которые можно теперь без труда внести после первого PR).

Что думаете?

2021-08-30 11:45 UTC, kpy3 commented on apps/hellgate/src/hg_payment_tool.erl
> +    setelement(Field, BCard, Value).
Я к этому и веду.

2021-08-30 11:59 UTC, kpy3 commented on apps/hellgate/src/hg_payment_tool.erl
> +) when PaymentSystem /= undefined ->
Очень странное и непонятное решение, зачем?

2021-08-30 12:04 UTC, arikai commented on apps/hellgate/src/hg_payment_tool.erl
> +    setelement(Field, BCard, Value).
@yuri-bukhalenkov 
PR в CAPI: https://github.com/rbkmoney/erlang_capi_v2/pull/568/
ИМХО код сырой, но идею работы с словарями и доменом и трифтом впринципе доносит

--- 

@yuri-bukhalenkov, проблемно будет разделить этот PR на 2 части (рефакторинг и фича)? КМК, может быть неплохой практикой для распиливания таких монументальных работ.

2021-08-30 12:04 UTC, kpy3 commented on apps/hellgate/src/hg_payment_tool.erl
> +get_possible_methods({bank_card, #domain_BankCard{payment_system = PS} = BankCard}) when PS /= undefined ->
Адаптеры проверяют сами, сначала смотрят на новые поля, если они не заполнены, то на старые значения. Такая логика сейчас, но я бы не закладывался на это, а просто передавал всё что у нас есть (и старое и новое значение), пусть они сами решают каким им пользоваться (просто потому что адаптеров под сотню и наверняка какие-то легаси работают по-старому, мы этого не знаем). А HG стоит между адаптерами и апишечками, которые работают со справочниками. По-сути передатчик.

@keynslug поправь меня если я не прав.

2021-08-30 12:12 UTC, yuri-bukhalenkov commented on apps/hellgate/src/hg_payment_tool.erl
> +    setelement(Field, BCard, Value).
Поймите, специально, потому что не нравится я не рефакторю, я максимально стараюсь придерживаться идеей не вмешательства в чужой код. А что делать когда в процессе внесения нового функционала понимаешь, что без небольшого изменения - жопа, либо по результату, либо по внешнему виду? Ревертить всё что до этого написал? Оформлять отдельный ПР по рефакторингу, дождаться когда его всё-таки заапрувят, а потооооом, начинать начинать пилить новый функционал? Мне кажется или нет, что у нас со сроками не ахти? Или ломая пальцы пытаться впихнуть невпихуемое? У нас ревьюер - священная корова? Мне за пивом сбегать? Имхо, ПР - это больше совместная работа, а не экзамен.

2021-08-30 12:58 UTC, arikai commented on apps/hellgate/src/hg_payment_tool.erl
> +    setelement(Field, BCard, Value).
> Поймите, специально, потому что не нравится я не рефакторю, я максимально стараюсь придерживаться идеей не вмешательства в чужой код.

Так нет же чужого кода: есть наш, и любой вправе его поменять.

>  А что делать когда в процессе внесения нового функционала понимаешь, что без небольшого изменения - жопа, либо по результату, либо по внешнему виду? Ревертить всё что до этого написал?

Зачастую это достаточно тривиально делается `git stash --patch`. 
Здесь же речь в первую очередь о размере PR (большие сложно читать). Если и рефакторинг, и фича набирают каждый по 400-500 строк – это повод задуматься.

В данном случае я вижу очень большое количество бойлерплейта, которое в идеале можно сократить: эта часть и так меняется, и я не вижу причин заодно не отрефакторить её. Но это может быть мой личный pet peeve :)

> Оформлять отдельный ПР по рефакторингу, дождаться когда его всё-таки заапрувят, а потооооом, начинать начинать пилить новый функционал?

Мой комментарий о разделении на 2 PR – лишь один из (идеальных) вариантов, и если сроки действительно жмут – придётся срезать углы.

> Оформлять отдельный ПР по рефакторингу, дождаться когда его всё-таки заапрувят, а потооооом, начинать начинать пилить новый функционал? 
> Мне кажется или нет, что у нас со сроками не ахти? Имхо, ПР - это больше совместная работа, а не экзамен.

Может быть немного наброс, но не находишь это взаимоисключающими параграфами? :) 
Если сроки действительно жмут, то это задача как ревьюера прокомментировать код, так и разработчика – сделать этот процесс максимально простым. 

Как микс фичи с фиксом форматирования на 1000 строк: в идеале было бы разделить, верно?

2021-08-30 13:05 UTC, arikai commented on apps/hellgate/src/hg_payment_tool.erl
> +    setelement(Field, BCard, Value).
```suggestion
payment_method(<<"card">>) ->
  bank_card;
payment_method(<<"payterm">>) ->
  payment_terminal;
payment_method(<<"wallet">>) ->
  digital_wallet;
payment_method(<<"crypto_currency">>) ->
  crypto_currency;
payment_method(<<"mobile_commerce">>) ->
  mobile_commerce.

set_payment_system(BCard, LegacyPSBin) when
    L =:= <<"visa">>;
    L =:= <<"mastercard">>;
    L =:= <<"visaelectron">>;
    L =:= <<"maestro">>;
    L =:= <<"forbrugsforeningen">>;
    L =:= <<"dankort">>;
    L =:= <<"amex">>;
    L =:= <<"dinersclub">>;
    L =:= <<"discover">>;
    L =:= <<"unionpay">>;
    L =:= <<"jcb">>;
    L =:= <<"nspkmir">>
->
    #domain_BankCard{payment_system_deprecated = binary_to_existing_atom(L)};
set_payment_system(BCard, PSBinRef) ->
    #domain_BankCard{payment_system = #domain_PaymentSystemRef{id = PSBinRef}}.
```

Как пример.
На самом деле это немного nitpick и лучше действительно отрефакторить это только если появится что-то вроде `thrift_meta`.

2021-08-30 13:13 UTC, yuri-bukhalenkov commented on apps/hellgate/src/hg_payment_tool.erl
> +    setelement(Field, BCard, Value).
> > Поймите, специально, потому что не нравится я не рефакторю, я максимально стараюсь придерживаться идеей не вмешательства в чужой код.
> 
> Так нет же чужого кода: есть наш, и любой вправе его поменять.
> 
> > А что делать когда в процессе внесения нового функционала понимаешь, что без небольшого изменения - жопа, либо по результату, либо по внешнему виду? Ревертить всё что до этого написал?
> 
> Зачастую это достаточно тривиально делается `git stash --patch`.
> Здесь же речь в первую очередь о размере PR (большие сложно читать). Если и рефакторинг, и фича набирают каждый по 400-500 строк – это повод задуматься.
> 
> В данном случае я вижу очень большое количество бойлерплейта, которое в идеале можно сократить: эта часть и так меняется, и я не вижу причин заодно не отрефакторить её. Но это может быть мой личный pet peeve :)
> 
> > Оформлять отдельный ПР по рефакторингу, дождаться когда его всё-таки заапрувят, а потооооом, начинать начинать пилить новый функционал?
> 
> Мой комментарий о разделении на 2 PR – лишь один из (идеальных) вариантов, и если сроки действительно жмут – придётся срезать углы.
> 
> > Оформлять отдельный ПР по рефакторингу, дождаться когда его всё-таки заапрувят, а потооооом, начинать начинать пилить новый функционал?
> > Мне кажется или нет, что у нас со сроками не ахти? Имхо, ПР - это больше совместная работа, а не экзамен.
> 
> Может быть немного наброс, но не находишь это взаимоисключающими параграфами? :)
> Если сроки действительно жмут, то это задача как ревьюера прокомментировать код, так и разработчика – сделать этот процесс максимально простым.
> 
> Как микс фичи с фиксом форматирования на 1000 строк: в идеале было бы разделить, верно?

Прости, пожалуйста, ничего не понял из твоих слов. Раздели их на разные ПР, а потом у нас тут так никто не пишет - надо бы переписать.

2021-08-30 13:20 UTC, arikai commented on apps/hellgate/src/hg_payment_tool.erl
> +    setelement(Field, BCard, Value).
TL;DR: мои мысли по поводу микса фич и рефакторинга. Здесь немного ошибся и всё не так критично: на мой взгляд стоит поправить некоторые места (как – см. suggestion выше), а остальное – вкусовщина.

2021-08-30 13:22 UTC, arikai commented on apps/hellgate/src/hg_payment_tool.erl
> +) when PaymentSystem /= undefined ->
Здесь поддержу: стоит придерживаться именования как минимум в рамках одной функции.

2021-08-30 14:10 UTC, kpy3 commented on apps/hellgate/src/hg_payment_tool.erl
> +get_possible_methods({bank_card, #domain_BankCard{payment_system = PS} = BankCard}) when PS /= undefined ->
В общем, в целом это должно работать, но может возникнуть проблема обратной совместимости с роутингом, если где-нибудь в capi-pcidss вдруг выпилят заполнение легаси полей в `#domain_BankCard{}`. Нужна будет либо миграция методов в `dominant` либо изменение работы `get_possible_methods/2`, либо и то и то.

2021-08-30 14:12 UTC, kpy3 submitted a review, later dismissed

2021-08-30 14:27 UTC, kpy3 commented
Пожалуй стоило бы добавить сюда ещё тестов для проверки работы с платёжными методами, которые используют справочники.

2021-08-30 14:41 UTC, yuri-bukhalenkov commented
> Пожалуй стоило бы добавить сюда ещё тестов для проверки работы с платёжными методами, которые используют справочники.

Да, я их планировал внести, ждал когда @arikai завершит аналогичную задачу в party-management. Имхо, апрув преждевременный, работа ещё не завершена. По ходу написания тестов может что-нить вылезти.

2021-08-30 15:02 UTC, kpy3 commented
> > Пожалуй стоило бы добавить сюда ещё тестов для проверки работы с платёжными методами, которые используют справочники.
> 
> Да, я их планировал внести, ждал когда @arikai завершит аналогичную задачу в party-management. Имхо, апрув преждевременный, работа ещё не завершена. По ходу написания тестов может что-нить вылезти.

Тогда оформи его как draft что ли, чтобы как будет готово смотреть всё сразу

2021-09-06 08:22 UTC, arikai commented on apps/hellgate/test/hg_direct_recurrent_tests_SUITE.erl
> +-export([not_exists_payment_test_new/1]).
Nitpick: `_new` не позволяет сразу понять, о чём идёт речь (тесты для нового представления платёжных сущностей).
Может, что-то вроде `_dict`?

2021-09-06 08:22 UTC, arikai commented on apps/hellgate/test/hg_direct_recurrent_tests_SUITE.erl
> +first_recurrent_payment_success_test(C, PmtSys) ->
🔥 огонь

2021-09-14 09:04 UTC, arikai approved these changes

2021-09-14 09:07 UTC, kpy3 commented on apps/hellgate/test/hg_invoice_tests_SUITE.erl
> +                                        definition = {crypto_currency_is, ?crypta(<<"bitcoin-ref">>)}
хм, а почему `?crypta`? 🙃 может всё же `?crypto`? 🤔

2021-09-14 09:09 UTC, yuri-bukhalenkov commented on apps/hellgate/test/hg_invoice_tests_SUITE.erl
> +                                        definition = {crypto_currency_is, ?crypta(<<"bitcoin-ref">>)}
ну, так неформально криптовалюты для краткости называют, я решил следовать канонам неформальности

2021-09-14 09:11 UTC, kpy3 approved these changes

2021-09-14 09:13 UTC, yuri-bukhalenkov commented
Всем спасибо!!!! СПАСИБИЩЕ!!!

2021-09-14 09:22 UTC, merged