ED-97: switching to external pm
rbkmoney/hellgate pull request #578
Opened 2021-06-22 08:17 UTC by yuri-bukhalenkov

2021-07-05 12:32 UTC, ndiezel0 requested changes

2021-07-05 12:32 UTC, ndiezel0 commented on apps/hellgate/test/hg_ct_helper.erl
> +    _ = timer:sleep(5000),
В итоге 5 секунд ему нужно? Или можно снизить?

2021-07-05 12:32 UTC, ndiezel0 commented on apps/hellgate/test/hg_ct_helper.erl
> +    "http://party-management:8022".
Я бы его использовал во всех местах, где упоминается хост ПМа, чтоб менять можно было в одном месте. И можно заменить эту функцию на макрос, если будет удобнее.

2021-07-05 12:32 UTC, ndiezel0 commented on apps/hellgate/test/hg_customer_tests_SUITE.erl
> +    _ = timer:sleep(5000),
Это тоже наверно можно снизить, экспериментальным путем можно установить.

2021-07-05 12:32 UTC, ndiezel0 commented on apps/hellgate/test/hg_invoice_template_tests_SUITE.erl
> +    Client = hg_client_party:start(PartyID, hg_ct_helper:create_client(PMRootUrl, PartyID)),
Может заменить использование таких прямых вызовов woody на использование `party_client`?

2021-07-05 12:35 UTC, yuri-bukhalenkov commented on apps/hellgate/test/hg_ct_helper.erl
> +    _ = timer:sleep(5000),
в каком-то из твоих коммитов было 3 сек, у меня локально тесты валились, увеличил до 5 - сработало. поэтому так и оставил.

2021-07-05 12:38 UTC, yuri-bukhalenkov commented on apps/hellgate/test/hg_customer_tests_SUITE.erl
> +    _ = timer:sleep(5000),
Напрягает, что при небольших значения тесты могут пройти, а могут и нет. Например, выдёргиваешь ноут из розетки, он переходит в режим энергосбережения и тесты уже не проходят.

2021-07-05 12:41 UTC, yuri-bukhalenkov commented on apps/hellgate/test/hg_ct_helper.erl
> +    "http://party-management:8022".
Оки, я посмотрю, но не должно быть - я ПМ из проекта удалил, тесты бы не прошли.

2021-07-05 12:42 UTC, yuri-bukhalenkov commented on apps/hellgate/test/hg_invoice_template_tests_SUITE.erl
> +    Client = hg_client_party:start(PartyID, hg_ct_helper:create_client(PMRootUrl, PartyID)),
Хорошо. Гляну. Это только в тестах ведь?

2021-07-05 15:11 UTC, ndiezel0 commented on apps/hellgate/test/hg_ct_helper.erl
> +    "http://party-management:8022".
Что не должно быть? Я не понял 😕

2021-07-05 15:12 UTC, ndiezel0 commented on apps/hellgate/test/hg_customer_tests_SUITE.erl
> +    _ = timer:sleep(5000),
Ок, можно тогда забить. Все равно с удалением PM тесты быстрее проходят.

2021-07-05 15:13 UTC, ndiezel0 commented on apps/hellgate/test/hg_invoice_template_tests_SUITE.erl
> +    Client = hg_client_party:start(PartyID, hg_ct_helper:create_client(PMRootUrl, PartyID)),
Ага, но если в где-то еще в hellgate использует такой прямой поход в ПМ в обход клиента, то тоже стоит заменить.

2021-07-05 19:15 UTC, yuri-bukhalenkov commented on apps/hellgate/test/hg_ct_helper.erl
> +    "http://party-management:8022".
ты писал: Я бы его использовал во всех местах. Предполагаю, если бы это было так, путь где-то был старый и тесты не прошли бы.

2021-07-08 17:33 UTC, yuri-bukhalenkov commented on apps/hellgate/test/hg_ct_helper.erl
> +    "http://party-management:8022".
готово

2021-07-08 17:33 UTC, yuri-bukhalenkov commented on apps/hellgate/test/hg_invoice_template_tests_SUITE.erl
> +    Client = hg_client_party:start(PartyID, hg_ct_helper:create_client(PMRootUrl, PartyID)),
готово

2021-07-12 08:25 UTC, ndiezel0 approved these changes

2021-07-26 09:59 UTC, merged