ED-157: impl payment cascading for limit overflow
rbkmoney/hellgate pull request #581
Opened 2021-07-02 05:44 UTC by 0x42

2021-07-05 11:25 UTC, WWWcool commented on apps/hellgate/src/hg_invoice_payment.erl
> +            RejectedRoutes1 = [{PRef, {'LimitOverflow', undefined}} | RejectedRoutes0],
или раз уж не хочется конкретизировать, то хотя бы в функцию это вынести чтобы была одна точка

2021-07-05 11:25 UTC, WWWcool commented on apps/hellgate/src/hg_invoice_payment.erl
> +            Events = [?payment_started(Payment)],
ого, очень жестко, нужно над этим еще подумать

2021-07-05 11:25 UTC, WWWcool commented on apps/hellgate/src/hg_limiter.erl
> +                amount => LimiterAmount,
```suggestion
                amount => LimitAmount,
```
мб?

2021-07-05 11:25 UTC, WWWcool commented on apps/hellgate/src/hg_limiter.erl
> +print_overflowing_limits(OverflowingLimits) ->
как только лимит переполнился то у нас весь рейт платежей по этому провайдеру засирает мощно лог -- это точно нужно?

2021-07-05 11:25 UTC, WWWcool commented on apps/hellgate/test/hg_invoice_tests_SUITE.erl
> +    ?assertMatch(#limiter_Limit{amount = ?LIMIT_UPPER_BOUNDARY}, Limit).
а что эта проверка проверяет?

2021-07-05 15:58 UTC, kpy3 commented on apps/hellgate/src/hg_invoice.erl
> +    #st{activity = _Activity} = collapse_history(unmarshal_history(History)),
А в чём тайный смысл `_Activity`?

2021-07-05 16:09 UTC, kpy3 commented on apps/hellgate/src/hg_invoice_payment.erl
> +    PrevRoutes = get_route_history(St),
```suggestion
```

2021-07-05 16:11 UTC, kpy3 commented on apps/hellgate/src/hg_invoice_payment.erl
> +
```suggestion
                PrevRoutes = get_route_history(St),
```

2021-07-05 16:12 UTC, kpy3 requested changes
Кажется так будет лучше: 1) Ближе к использованию и 2) вычислится когда необходимо (провалится в ветку case'a)

2021-07-05 16:21 UTC, kpy3 requested changes
Кажется так понятнее будет что в этой переменной находится

2021-07-05 16:21 UTC, kpy3 commented on apps/hellgate/src/hg_invoice_payment.erl
> +    FindUsedRouteFun = lists:search(
```suggestion
    UsedRoute = lists:search(
```

2021-07-05 16:21 UTC, kpy3 commented on apps/hellgate/src/hg_invoice_payment.erl
> +    case FindUsedRouteFun of
```suggestion
    case UsedRoute of
```

2021-07-05 16:23 UTC, kpy3 commented on apps/hellgate/src/hg_invoice_payment.erl
> +        _ ->
```suggestion
        false ->
```
Тут других вариантов не может быть, согласно спецификации 🙃

2021-07-05 19:27 UTC, kpy3 commented on apps/hellgate/src/hg_invoice_payment.erl
> +    {Routes, RejectContext};
Кстати, в порядке следования роутов порядок важен? Если важен, то кажется тут надо перевернуть список 🤔

2021-07-05 19:57 UTC, kpy3 commented on apps/hellgate/src/hg_limiter.erl
> +                    {[LimitID | AccIn], OverflowLimits}
Хм, а это точно корректно? Кажется, если лимит не найден, надо бежать конфиг чинить, иначе этот ид протечёт выше и где-нибудь выстрелит в другом месте, нет? 🤔

2021-07-06 04:51 UTC, 0x42 commented on apps/hellgate/src/hg_invoice_payment.erl
> +    IsFirstAttempt(Attempt).
Попытка была избежать магических чисел и сделать код самодокументируемым.

2021-07-06 04:57 UTC, 0x42 commented on apps/hellgate/src/hg_limiter.erl
> +                    {[LimitID | AccIn], OverflowLimits}
У нас ленивой создание лимитов.

2021-07-06 06:53 UTC, kpy3 commented on apps/hellgate/src/hg_invoice_payment.erl
> +    IsFirstAttempt(Attempt).
Может тогда лучше сразу сделать функцию `-spec is_first_attempt(st()) -> boolean()`, которая и будет нужный признак возвращать? 🤔

2021-07-06 10:43 UTC, 0x42 commented on apps/hellgate/src/hg_invoice_payment.erl
> +    IsFirstAttempt(Attempt).
Мне показалось, что &#955; лучше подойдет для этого тк используется  в одном месте.

2021-07-06 10:49 UTC, 0x42 commented on apps/hellgate/src/hg_invoice_payment.erl
> +    FindUsedRouteFun = lists:search(
Согласен, раньше там fun() была, которая была переписана, а вот название прозевал.

2021-07-07 13:38 UTC, 0x42 commented on apps/hellgate/src/hg_limiter.erl
> +print_overflowing_limits(OverflowingLimits) ->
А если не лимит не переполнен, мы будем при первой попытке проходить по списку провайдеров и проверять их лимиты, что будет порождать кучу логов. Для понимания почему был выбран данный роут, а не предыдущей было бы полезно увидеть информацию

2021-07-07 14:21 UTC, 0x42 commented on apps/hellgate/src/hg_invoice.erl
> +    #st{activity = _Activity} = collapse_history(unmarshal_history(History)),
Забытое

2021-07-07 15:26 UTC, 0x42 commented on apps/hellgate/src/hg_invoice_payment.erl
> +    {Routes, RejectContext};
На данном этапе порядок следования роутов неважен. Тк после фильтрации роутов мы перейдем к шагу выбора роута hg_routing:choose_route(...) в котором уже будем выбирать взависимости от приоритета, доступности и тд.

2021-07-08 06:18 UTC, 0x42 commented on apps/hellgate/src/hg_invoice_payment.erl
> +                        RejectedProvOut = [{ProviderRef, {'LimitOverflow', undefined}} | RejectedProvIn],
Добавил  список id переполненных лимитов, убрал pring_oveflowing_limits. Пожалуй логирование  здесь будет лишним.

2021-07-08 15:15 UTC, 0x42 commented
9688918 добавил событие payment_route_decllined по которому переводим activity в {payment, risk_scoring}

2021-07-09 09:17 UTC, WWWcool reviewed
особых замечаний нет, только миноры

2021-07-09 09:17 UTC, WWWcool commented on apps/hellgate/src/hg_invoice_payment.erl
> +    IsFirstAttempt(Attempt).
в итоге лямбду чтоль оставили? просто выглядит достаточно странно, как будто оверинжиниринг - можно же просто кейс использовать

2021-07-09 09:17 UTC, WWWcool commented on apps/hellgate/src/hg_invoice_payment.erl
> +    [R || R <- Routes, RouteNotUsedFun(R)].
я не силен в этой записи, но реально так отфильтрует?)

2021-07-09 09:17 UTC, WWWcool commented on apps/hellgate/src/hg_invoice_payment.erl
> +    _ = logger:warning(Text, [PRef, <<"LimitOverflow">>, LimitIDs]).
```suggestion
    Text = "The provider with ref ~p has been rejected: LimitOverflow, limit id: ~p",
    _ = logger:warning(Text, [PRef, LimitIDs]).
```

2021-07-09 09:17 UTC, WWWcool commented on apps/hellgate/src/hg_invoice_payment.erl
> +        target = ?processed(),
странно что здесь такой таргер

2021-07-09 09:17 UTC, WWWcool commented on apps/hellgate/src/hg_invoice_payment.erl
> +%% TODO[limiter] cascading: it is temporary ugly decesion, it should be rewrite in full limiter integration
актуален ли этот коммент теперь?

2021-07-09 13:11 UTC, kpy3 commented on apps/hellgate/src/hg_invoice_payment.erl
> +    [R || R <- Routes, RouteNotUsedFun(R)].
Почему нет? :)
```
1> F = fun(T) -> T =:= false end.
#Fun<erl_eval.44.40011524>
2> [T || T <- [true, true, false, true], F(T)].
[false]
```

2021-07-09 15:07 UTC, 0x42 commented on apps/hellgate/src/hg_invoice_payment.erl
> +    [R || R <- Routes, RouteNotUsedFun(R)].
> просто выглядит достаточно странно 

Чтож если предложенное решение и аргументы  смущает более одного человека тогда нужно переделать

2021-07-09 15:12 UTC, 0x42 commented on apps/hellgate/src/hg_invoice_payment.erl
> +    [R || R <- Routes, RouteNotUsedFun(R)].
> я не силен в этой записи, но реально так отфильтрует?)

https://erlang.org/doc/programming_examples/list_comprehensions.html

``` erlang
[R || R <- Routes, RouteNotUsedFun(R)].
```
RouteNotUsedFun(R) это фильтр, если true то R добавляется в список иначе отсеивается.

2021-07-12 11:45 UTC, 0x42 commented on apps/hellgate/src/hg_invoice_payment.erl
> +        target = ?processed(),
Таргет здесь такой же как и для `{payment, risk_scoring}`, тк мы хотим заново вычислить роут

2021-07-12 12:40 UTC, 0x42 commented on apps/hellgate/src/hg_invoice_payment.erl
> +        target = ?processed(),
Скорее его здесь вообще не должно быть

2021-07-12 16:11 UTC, keynslug commented on apps/hellgate/src/hg_invoice_payment.erl
> +check_limit_overflow(Failure) ->
Эта функция будет возвращать `true` в ситуациях, когда ни о каких лимитах на нашей стороне речи даже не было, но адаптер в качестве кода ошибки неуспеха сессии вернул `authorization_failed:provider_limit_exceeded`.

2021-07-12 16:11 UTC, keynslug commented on apps/hellgate/src/hg_invoice_payment.erl
>      case hg_limiter:check_limits(TurnoverLimits, Invoice, Payment) of
Если мы только что захолдировали, то:
* не должны ли мы полученный clock использовать?
* всегда ли холд к этому моменту проверки уже будет учтён?

2021-07-12 16:11 UTC, keynslug commented on apps/hellgate/include/payment_events.hrl
> +).
Как я понимаю, мы можем обойтись и без нового ивента, если будем действовать как-то так:
1. Получили список провайдеров-кандидатов на первом этапе роутинга.
2. Отсеяли тех, у кого лимит уже превышен.
3. Захолдировали лимиты _у всех_ оставшихся кандидатов, отсеяли тех, у кого в результате лимит превышен, откатили у всех кроме выбранного на втором этапе роутинга провайдера.

Правильно ли я понимаю? Схема на первый взгляд выглядит устойчивой к ретраям.

2021-07-13 11:02 UTC, WWWcool commented on apps/hellgate/src/hg_invoice_payment.erl
> +        0 ->
это мое предложение - у нас проверка лимитов состоит из двух частей - при первом заходе грубо фильтруем всех провайдеров у которых переполнено, чтобы повысить шанс прохода сразу, а потом если уж не прошло, то идем по всем уже без этой масштабной проверки

2021-07-13 11:03 UTC, WWWcool commented on apps/hellgate/src/hg_invoice_payment.erl
> +        construct_payment_plan_id(Invoice, Payment, Attempt),
иначе придется в план проводок докладывать всю историю всех попыток

2021-07-13 11:03 UTC, WWWcool commented on apps/hellgate/src/hg_invoice_payment.erl
> +    ok = hg_limiter:hold_payment_limits(TurnoverLimits, Invoice, Payment, Attempt),
там под капотом тот же шамвей -- поэтому для тех же что и выше

2021-07-13 11:05 UTC, WWWcool commented on apps/hellgate/include/payment_events.hrl
> +).
с такой схемой каскадинг не нужен))) потому что ты гарантируешь что выберешь провайдера у которого лимит пройдет, иначе такого провайдера нет -- вот где ты был с такими хорошими предложениями раньше))

2021-07-13 11:52 UTC, keynslug commented on apps/hellgate/src/hg_invoice_payment.erl
> +        construct_payment_plan_id(Invoice, Payment, Attempt),
Это вдогонку к https://github.com/rbkmoney/hellgate/pull/581#discussion_r668046126. Если отделить проверку лимитов от работы с cashflow, то я не вижу необходимости.

2021-07-13 11:57 UTC, keynslug commented on apps/hellgate/include/payment_events.hrl
> +).
Каскадинг – сложна, а задача вроде решена, чего ещё желать. 👴🏼 

Не, ну тут понятно, что в попытке избежать нового ивента мы будем сильнее (сложно оценить, но кажется немного) долбить лимитер. Плюс новый ивент всё равно нужен, если лимитер под капотом будет асинхронный, в котором между холдом и результирующим балансом некоторое количество времени должно пройти. У меня вопрос даже был скорее в том, корректно ли моё предположение.

2021-07-13 12:04 UTC, 0x42 commented on apps/hellgate/src/hg_invoice_payment.erl
> +    ok = hg_limiter:hold_payment_limits(TurnoverLimits, Invoice, Payment, Attempt),
Attempt позволяет решить проблему уникальности (plan_id)[https://github.com/rbkmoney/damsel/blob/04dfc996dde53d4690758053cd5c477408faeb1a/proto/accounter.thrift#L77]

2021-07-13 12:27 UTC, 0x42 commented on apps/hellgate/src/hg_invoice_payment.erl
> +        0 ->
Хотелось сократить лишние запросы(в др микросервисы) если рассматривать случай когда у мерчанта вычислен список из 10+ роутов. (рандомный анализ логов говорит что один запрос в шамвей стоит 24 ms)

2021-07-13 12:58 UTC, keynslug commented on apps/hellgate/src/hg_invoice_payment.erl
> +        0 ->
Я не понимаю здесь, что значит _лишние_. Если они _лишние_, то зачем их вообще делать?

2021-07-13 12:59 UTC, keynslug commented on apps/hellgate/src/hg_invoice_payment.erl
> +        0 ->
> при первом заходе грубо фильтруем всех провайдеров у которых переполнено, чтобы повысить шанс прохода сразу, а потом если уж не прошло, то идем по всем уже без этой масштабной проверки

Понял мысль. Но нужен коммент тогда.

2021-07-13 13:02 UTC, keynslug commented on apps/hellgate/src/hg_invoice_payment.erl
> +    ok = hg_limiter:hold_payment_limits(TurnoverLimits, Invoice, Payment, Attempt),
То есть ситуация вида _холдируем уже зароллбеченный план_?

2021-07-13 16:14 UTC, keynslug commented on apps/hellgate/include/payment_events.hrl
> +).
> Нам нужно будет в евентах передавать список всех роутов(а для этого необходимы правки в event'ы)

Зачем он в ивентах? Мы же его всегда можем вычислить.

2021-07-13 17:00 UTC, 0x42 commented on apps/hellgate/include/payment_events.hrl
> +).
Нам не нужен список роутов, когда мы будем делать холд в аакаунтере тк на этом этапе работы с лимитером не будет(если использовать предложенный вариант). 

Проверка + Холд всех роутов позволяет исключить возможные проблемы в случае ретраев.
Мне вариант нравиться, если мы готовы закрыть глаза на возможную просадку таймингов по платежам

2021-07-13 20:35 UTC, WWWcool commented on apps/hellgate/include/payment_events.hrl
> +).
про событие лимитера -- это к другой задаче про полную интеграцию - там как раз это решается, а здесь можно тогда обойтись предложенным решением - мне оно тоже нравится и главное на мой вкус - оно не запутывает граф процесса платежа - все остается так же линейно.

2021-07-13 20:35 UTC, WWWcool commented on apps/hellgate/src/hg_invoice_payment.erl
>      case hg_limiter:check_limits(TurnoverLimits, Invoice, Payment) of
в текущей реализации клок игнорим

2021-07-13 20:36 UTC, WWWcool commented on apps/hellgate/src/hg_invoice_payment.erl
> +    ok = hg_limiter:hold_payment_limits(TurnoverLimits, Invoice, Payment, Attempt),
ситуация вида - нужно проверить больше одного лимита на платеж

2021-07-13 20:50 UTC, WWWcool commented on apps/hellgate/src/hg_invoice_payment.erl
> +    ok = hg_limiter:hold_payment_limits(TurnoverLimits, Invoice, Payment, Attempt),
если это так - то это не работает, потому что у нас есть список роутов и мы не идем по нему два раза

2021-07-14 14:47 UTC, keynslug commented on apps/hellgate/include/payment_events.hrl
> +).
> Первое что бросается в глаза это заведомо лишние походы в лимитер (вдруг у мерча будет 10 потенциальных роутов, это 18 лишних запросов).

Безусловно. Но как я понимаю, реалистичная ситуация (сейчас по крайней мере) − это два, максимум три роута с лимитами на магазин мерчанта. Поправьте, если неправильно оценил.

> Проверка + Холд всех роутов позволяет исключить возможные проблемы в случае ретраев.

Я тут кажется просрался в своём первом комменте. Кажется шаг 2 (Отсеяли тех, у кого лимит уже превышен) ломает ретраибельность.

Пример: платёж на 100₽, у нас три кандидата, в порядке приоритета:
* кандидат 1 с лимитом в 200₽ и текущим значением 150₽,
* кандидат 2 с лимитом в 1000₽ и текущим значением 0₽,
* кандидат 3 без лимитов.

Если следовать логике из коммента, то в первый раз на этапе проверки лимитов мы:

1. Получаем трёх кандидатов.
2. Проверяем лимиты и никого не отсеиваем, потому что текущие значения у двух кандидатов с лимитами не превышают лимит.
3. Холдируем лимиты у двух кандидатов.
4. ...И hellgate падает.

То после ретрая мы _отсеем_ кандидата 2, и никто больше никогда не расхолдирует холд с предыдущей попытки.

Поэтому схема с шагом 2 не работает. Но вроде бы работает без него.

2021-07-15 22:41 UTC, 0x42 commented on apps/hellgate/include/payment_events.hrl
> +).
Тк нельзя делать hold после rollback(ограничение schumway), появилась идея вынести rollback на отдельный этап при вычисление cashflow. Проблемы  которые возникнут:
1) при выкатке мы получим часть машин у которых этап вычисления роута выполнялся со старой версией кода(без hold'ов в limiter). А шаг вычисления cashflow будет с новым кодом(rollback всех hold кроме выбраного rout'а). Это нам грозит 500'ми.
2) проблемы сопровождения(внесение изменений в код) кода отвечающего за вычисление списка роутов. потенциально может грозить потерянными холдами. Например после внесения изменений список роутов может стать короче: 
    a) шаг "compute_route"
        [R1, R2, R3] = compute_route()старый код, hold([R1, R2, R3]); 
    ----- !!! выкатка !!! -------- 
    c) [R1, R2] = compute_route() новый код, hold(R1, R2);
>>> в лимитере захолдированы R1, R2, R3
    d) шаг "cashflow_building"
        [R1, R2] = compute_route() новый код    
        rollback(R2)

2021-08-10 07:18 UTC, closed without merging